// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"entgo.io/ent"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the subscription type in the database.
	Label = "subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldEntID holds the string denoting the ent_id field in the database.
	FieldEntID = "ent_id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldPackageName holds the string denoting the package_name field in the database.
	FieldPackageName = "package_name"
	// FieldUsdPrice holds the string denoting the usd_price field in the database.
	FieldUsdPrice = "usd_price"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldPackageType holds the string denoting the package_type field in the database.
	FieldPackageType = "package_type"
	// FieldCredit holds the string denoting the credit field in the database.
	FieldCredit = "credit"
	// FieldResetType holds the string denoting the reset_type field in the database.
	FieldResetType = "reset_type"
	// FieldQPSLimit holds the string denoting the qps_limit field in the database.
	FieldQPSLimit = "qps_limit"
	// Table holds the table name of the subscription in the database.
	Table = "subscriptions"
)

// Columns holds all SQL columns for subscription fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldEntID,
	FieldAppID,
	FieldPackageName,
	FieldUsdPrice,
	FieldDescription,
	FieldSortOrder,
	FieldPackageType,
	FieldCredit,
	FieldResetType,
	FieldQPSLimit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/billing-middleware/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultEntID holds the default value on creation for the "ent_id" field.
	DefaultEntID func() uuid.UUID
	// DefaultAppID holds the default value on creation for the "app_id" field.
	DefaultAppID func() uuid.UUID
	// DefaultPackageName holds the default value on creation for the "package_name" field.
	DefaultPackageName string
	// DefaultUsdPrice holds the default value on creation for the "usd_price" field.
	DefaultUsdPrice decimal.Decimal
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder func() uint32
	// DefaultPackageType holds the default value on creation for the "package_type" field.
	DefaultPackageType string
	// DefaultCredit holds the default value on creation for the "credit" field.
	DefaultCredit func() uint32
	// DefaultResetType holds the default value on creation for the "reset_type" field.
	DefaultResetType string
	// DefaultQPSLimit holds the default value on creation for the "qps_limit" field.
	DefaultQPSLimit func() uint32
)
