// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/addon"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// AddonUpdate is the builder for updating Addon entities.
type AddonUpdate struct {
	config
	hooks     []Hook
	mutation  *AddonMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AddonUpdate builder.
func (au *AddonUpdate) Where(ps ...predicate.Addon) *AddonUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetCreatedAt sets the "created_at" field.
func (au *AddonUpdate) SetCreatedAt(u uint32) *AddonUpdate {
	au.mutation.ResetCreatedAt()
	au.mutation.SetCreatedAt(u)
	return au
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (au *AddonUpdate) SetNillableCreatedAt(u *uint32) *AddonUpdate {
	if u != nil {
		au.SetCreatedAt(*u)
	}
	return au
}

// AddCreatedAt adds u to the "created_at" field.
func (au *AddonUpdate) AddCreatedAt(u int32) *AddonUpdate {
	au.mutation.AddCreatedAt(u)
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AddonUpdate) SetUpdatedAt(u uint32) *AddonUpdate {
	au.mutation.ResetUpdatedAt()
	au.mutation.SetUpdatedAt(u)
	return au
}

// AddUpdatedAt adds u to the "updated_at" field.
func (au *AddonUpdate) AddUpdatedAt(u int32) *AddonUpdate {
	au.mutation.AddUpdatedAt(u)
	return au
}

// SetDeletedAt sets the "deleted_at" field.
func (au *AddonUpdate) SetDeletedAt(u uint32) *AddonUpdate {
	au.mutation.ResetDeletedAt()
	au.mutation.SetDeletedAt(u)
	return au
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (au *AddonUpdate) SetNillableDeletedAt(u *uint32) *AddonUpdate {
	if u != nil {
		au.SetDeletedAt(*u)
	}
	return au
}

// AddDeletedAt adds u to the "deleted_at" field.
func (au *AddonUpdate) AddDeletedAt(u int32) *AddonUpdate {
	au.mutation.AddDeletedAt(u)
	return au
}

// SetEntID sets the "ent_id" field.
func (au *AddonUpdate) SetEntID(u uuid.UUID) *AddonUpdate {
	au.mutation.SetEntID(u)
	return au
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (au *AddonUpdate) SetNillableEntID(u *uuid.UUID) *AddonUpdate {
	if u != nil {
		au.SetEntID(*u)
	}
	return au
}

// SetAppID sets the "app_id" field.
func (au *AddonUpdate) SetAppID(u uuid.UUID) *AddonUpdate {
	au.mutation.SetAppID(u)
	return au
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (au *AddonUpdate) SetNillableAppID(u *uuid.UUID) *AddonUpdate {
	if u != nil {
		au.SetAppID(*u)
	}
	return au
}

// ClearAppID clears the value of the "app_id" field.
func (au *AddonUpdate) ClearAppID() *AddonUpdate {
	au.mutation.ClearAppID()
	return au
}

// SetUsdPrice sets the "usd_price" field.
func (au *AddonUpdate) SetUsdPrice(d decimal.Decimal) *AddonUpdate {
	au.mutation.SetUsdPrice(d)
	return au
}

// SetNillableUsdPrice sets the "usd_price" field if the given value is not nil.
func (au *AddonUpdate) SetNillableUsdPrice(d *decimal.Decimal) *AddonUpdate {
	if d != nil {
		au.SetUsdPrice(*d)
	}
	return au
}

// ClearUsdPrice clears the value of the "usd_price" field.
func (au *AddonUpdate) ClearUsdPrice() *AddonUpdate {
	au.mutation.ClearUsdPrice()
	return au
}

// SetCredit sets the "credit" field.
func (au *AddonUpdate) SetCredit(u uint32) *AddonUpdate {
	au.mutation.ResetCredit()
	au.mutation.SetCredit(u)
	return au
}

// SetNillableCredit sets the "credit" field if the given value is not nil.
func (au *AddonUpdate) SetNillableCredit(u *uint32) *AddonUpdate {
	if u != nil {
		au.SetCredit(*u)
	}
	return au
}

// AddCredit adds u to the "credit" field.
func (au *AddonUpdate) AddCredit(u int32) *AddonUpdate {
	au.mutation.AddCredit(u)
	return au
}

// ClearCredit clears the value of the "credit" field.
func (au *AddonUpdate) ClearCredit() *AddonUpdate {
	au.mutation.ClearCredit()
	return au
}

// SetSortOrder sets the "sort_order" field.
func (au *AddonUpdate) SetSortOrder(u uint32) *AddonUpdate {
	au.mutation.ResetSortOrder()
	au.mutation.SetSortOrder(u)
	return au
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (au *AddonUpdate) SetNillableSortOrder(u *uint32) *AddonUpdate {
	if u != nil {
		au.SetSortOrder(*u)
	}
	return au
}

// AddSortOrder adds u to the "sort_order" field.
func (au *AddonUpdate) AddSortOrder(u int32) *AddonUpdate {
	au.mutation.AddSortOrder(u)
	return au
}

// ClearSortOrder clears the value of the "sort_order" field.
func (au *AddonUpdate) ClearSortOrder() *AddonUpdate {
	au.mutation.ClearSortOrder()
	return au
}

// SetEnabled sets the "enabled" field.
func (au *AddonUpdate) SetEnabled(b bool) *AddonUpdate {
	au.mutation.SetEnabled(b)
	return au
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (au *AddonUpdate) SetNillableEnabled(b *bool) *AddonUpdate {
	if b != nil {
		au.SetEnabled(*b)
	}
	return au
}

// ClearEnabled clears the value of the "enabled" field.
func (au *AddonUpdate) ClearEnabled() *AddonUpdate {
	au.mutation.ClearEnabled()
	return au
}

// SetDescription sets the "description" field.
func (au *AddonUpdate) SetDescription(s string) *AddonUpdate {
	au.mutation.SetDescription(s)
	return au
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (au *AddonUpdate) SetNillableDescription(s *string) *AddonUpdate {
	if s != nil {
		au.SetDescription(*s)
	}
	return au
}

// ClearDescription clears the value of the "description" field.
func (au *AddonUpdate) ClearDescription() *AddonUpdate {
	au.mutation.ClearDescription()
	return au
}

// Mutation returns the AddonMutation object of the builder.
func (au *AddonUpdate) Mutation() *AddonMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AddonUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := au.defaults(); err != nil {
		return 0, err
	}
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AddonMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AddonUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AddonUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AddonUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AddonUpdate) defaults() error {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		if addon.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized addon.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := addon.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (au *AddonUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AddonUpdate {
	au.modifiers = append(au.modifiers, modifiers...)
	return au
}

func (au *AddonUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   addon.Table,
			Columns: addon.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: addon.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCreatedAt,
		})
	}
	if value, ok := au.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCreatedAt,
		})
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldUpdatedAt,
		})
	}
	if value, ok := au.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldUpdatedAt,
		})
	}
	if value, ok := au.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldDeletedAt,
		})
	}
	if value, ok := au.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldDeletedAt,
		})
	}
	if value, ok := au.mutation.EntID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: addon.FieldEntID,
		})
	}
	if value, ok := au.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: addon.FieldAppID,
		})
	}
	if au.mutation.AppIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: addon.FieldAppID,
		})
	}
	if value, ok := au.mutation.UsdPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: addon.FieldUsdPrice,
		})
	}
	if au.mutation.UsdPriceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Column: addon.FieldUsdPrice,
		})
	}
	if value, ok := au.mutation.Credit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCredit,
		})
	}
	if value, ok := au.mutation.AddedCredit(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCredit,
		})
	}
	if au.mutation.CreditCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: addon.FieldCredit,
		})
	}
	if value, ok := au.mutation.SortOrder(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldSortOrder,
		})
	}
	if value, ok := au.mutation.AddedSortOrder(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldSortOrder,
		})
	}
	if au.mutation.SortOrderCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: addon.FieldSortOrder,
		})
	}
	if value, ok := au.mutation.Enabled(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: addon.FieldEnabled,
		})
	}
	if au.mutation.EnabledCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: addon.FieldEnabled,
		})
	}
	if value, ok := au.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: addon.FieldDescription,
		})
	}
	if au.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: addon.FieldDescription,
		})
	}
	_spec.Modifiers = au.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{addon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AddonUpdateOne is the builder for updating a single Addon entity.
type AddonUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AddonMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (auo *AddonUpdateOne) SetCreatedAt(u uint32) *AddonUpdateOne {
	auo.mutation.ResetCreatedAt()
	auo.mutation.SetCreatedAt(u)
	return auo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableCreatedAt(u *uint32) *AddonUpdateOne {
	if u != nil {
		auo.SetCreatedAt(*u)
	}
	return auo
}

// AddCreatedAt adds u to the "created_at" field.
func (auo *AddonUpdateOne) AddCreatedAt(u int32) *AddonUpdateOne {
	auo.mutation.AddCreatedAt(u)
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AddonUpdateOne) SetUpdatedAt(u uint32) *AddonUpdateOne {
	auo.mutation.ResetUpdatedAt()
	auo.mutation.SetUpdatedAt(u)
	return auo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (auo *AddonUpdateOne) AddUpdatedAt(u int32) *AddonUpdateOne {
	auo.mutation.AddUpdatedAt(u)
	return auo
}

// SetDeletedAt sets the "deleted_at" field.
func (auo *AddonUpdateOne) SetDeletedAt(u uint32) *AddonUpdateOne {
	auo.mutation.ResetDeletedAt()
	auo.mutation.SetDeletedAt(u)
	return auo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableDeletedAt(u *uint32) *AddonUpdateOne {
	if u != nil {
		auo.SetDeletedAt(*u)
	}
	return auo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (auo *AddonUpdateOne) AddDeletedAt(u int32) *AddonUpdateOne {
	auo.mutation.AddDeletedAt(u)
	return auo
}

// SetEntID sets the "ent_id" field.
func (auo *AddonUpdateOne) SetEntID(u uuid.UUID) *AddonUpdateOne {
	auo.mutation.SetEntID(u)
	return auo
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableEntID(u *uuid.UUID) *AddonUpdateOne {
	if u != nil {
		auo.SetEntID(*u)
	}
	return auo
}

// SetAppID sets the "app_id" field.
func (auo *AddonUpdateOne) SetAppID(u uuid.UUID) *AddonUpdateOne {
	auo.mutation.SetAppID(u)
	return auo
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableAppID(u *uuid.UUID) *AddonUpdateOne {
	if u != nil {
		auo.SetAppID(*u)
	}
	return auo
}

// ClearAppID clears the value of the "app_id" field.
func (auo *AddonUpdateOne) ClearAppID() *AddonUpdateOne {
	auo.mutation.ClearAppID()
	return auo
}

// SetUsdPrice sets the "usd_price" field.
func (auo *AddonUpdateOne) SetUsdPrice(d decimal.Decimal) *AddonUpdateOne {
	auo.mutation.SetUsdPrice(d)
	return auo
}

// SetNillableUsdPrice sets the "usd_price" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableUsdPrice(d *decimal.Decimal) *AddonUpdateOne {
	if d != nil {
		auo.SetUsdPrice(*d)
	}
	return auo
}

// ClearUsdPrice clears the value of the "usd_price" field.
func (auo *AddonUpdateOne) ClearUsdPrice() *AddonUpdateOne {
	auo.mutation.ClearUsdPrice()
	return auo
}

// SetCredit sets the "credit" field.
func (auo *AddonUpdateOne) SetCredit(u uint32) *AddonUpdateOne {
	auo.mutation.ResetCredit()
	auo.mutation.SetCredit(u)
	return auo
}

// SetNillableCredit sets the "credit" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableCredit(u *uint32) *AddonUpdateOne {
	if u != nil {
		auo.SetCredit(*u)
	}
	return auo
}

// AddCredit adds u to the "credit" field.
func (auo *AddonUpdateOne) AddCredit(u int32) *AddonUpdateOne {
	auo.mutation.AddCredit(u)
	return auo
}

// ClearCredit clears the value of the "credit" field.
func (auo *AddonUpdateOne) ClearCredit() *AddonUpdateOne {
	auo.mutation.ClearCredit()
	return auo
}

// SetSortOrder sets the "sort_order" field.
func (auo *AddonUpdateOne) SetSortOrder(u uint32) *AddonUpdateOne {
	auo.mutation.ResetSortOrder()
	auo.mutation.SetSortOrder(u)
	return auo
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableSortOrder(u *uint32) *AddonUpdateOne {
	if u != nil {
		auo.SetSortOrder(*u)
	}
	return auo
}

// AddSortOrder adds u to the "sort_order" field.
func (auo *AddonUpdateOne) AddSortOrder(u int32) *AddonUpdateOne {
	auo.mutation.AddSortOrder(u)
	return auo
}

// ClearSortOrder clears the value of the "sort_order" field.
func (auo *AddonUpdateOne) ClearSortOrder() *AddonUpdateOne {
	auo.mutation.ClearSortOrder()
	return auo
}

// SetEnabled sets the "enabled" field.
func (auo *AddonUpdateOne) SetEnabled(b bool) *AddonUpdateOne {
	auo.mutation.SetEnabled(b)
	return auo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableEnabled(b *bool) *AddonUpdateOne {
	if b != nil {
		auo.SetEnabled(*b)
	}
	return auo
}

// ClearEnabled clears the value of the "enabled" field.
func (auo *AddonUpdateOne) ClearEnabled() *AddonUpdateOne {
	auo.mutation.ClearEnabled()
	return auo
}

// SetDescription sets the "description" field.
func (auo *AddonUpdateOne) SetDescription(s string) *AddonUpdateOne {
	auo.mutation.SetDescription(s)
	return auo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (auo *AddonUpdateOne) SetNillableDescription(s *string) *AddonUpdateOne {
	if s != nil {
		auo.SetDescription(*s)
	}
	return auo
}

// ClearDescription clears the value of the "description" field.
func (auo *AddonUpdateOne) ClearDescription() *AddonUpdateOne {
	auo.mutation.ClearDescription()
	return auo
}

// Mutation returns the AddonMutation object of the builder.
func (auo *AddonUpdateOne) Mutation() *AddonMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AddonUpdateOne) Select(field string, fields ...string) *AddonUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Addon entity.
func (auo *AddonUpdateOne) Save(ctx context.Context) (*Addon, error) {
	var (
		err  error
		node *Addon
	)
	if err := auo.defaults(); err != nil {
		return nil, err
	}
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AddonMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, auo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Addon)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AddonMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AddonUpdateOne) SaveX(ctx context.Context) *Addon {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AddonUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AddonUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AddonUpdateOne) defaults() error {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		if addon.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized addon.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := addon.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (auo *AddonUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AddonUpdateOne {
	auo.modifiers = append(auo.modifiers, modifiers...)
	return auo
}

func (auo *AddonUpdateOne) sqlSave(ctx context.Context) (_node *Addon, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   addon.Table,
			Columns: addon.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: addon.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Addon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, addon.FieldID)
		for _, f := range fields {
			if !addon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != addon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCreatedAt,
		})
	}
	if value, ok := auo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCreatedAt,
		})
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldUpdatedAt,
		})
	}
	if value, ok := auo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldUpdatedAt,
		})
	}
	if value, ok := auo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldDeletedAt,
		})
	}
	if value, ok := auo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldDeletedAt,
		})
	}
	if value, ok := auo.mutation.EntID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: addon.FieldEntID,
		})
	}
	if value, ok := auo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: addon.FieldAppID,
		})
	}
	if auo.mutation.AppIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: addon.FieldAppID,
		})
	}
	if value, ok := auo.mutation.UsdPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: addon.FieldUsdPrice,
		})
	}
	if auo.mutation.UsdPriceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Column: addon.FieldUsdPrice,
		})
	}
	if value, ok := auo.mutation.Credit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCredit,
		})
	}
	if value, ok := auo.mutation.AddedCredit(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldCredit,
		})
	}
	if auo.mutation.CreditCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: addon.FieldCredit,
		})
	}
	if value, ok := auo.mutation.SortOrder(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldSortOrder,
		})
	}
	if value, ok := auo.mutation.AddedSortOrder(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: addon.FieldSortOrder,
		})
	}
	if auo.mutation.SortOrderCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: addon.FieldSortOrder,
		})
	}
	if value, ok := auo.mutation.Enabled(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: addon.FieldEnabled,
		})
	}
	if auo.mutation.EnabledCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: addon.FieldEnabled,
		})
	}
	if value, ok := auo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: addon.FieldDescription,
		})
	}
	if auo.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: addon.FieldDescription,
		})
	}
	_spec.Modifiers = auo.modifiers
	_node = &Addon{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{addon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
