// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/usersubscription"
	"github.com/google/uuid"
)

// UserSubscriptionUpdate is the builder for updating UserSubscription entities.
type UserSubscriptionUpdate struct {
	config
	hooks     []Hook
	mutation  *UserSubscriptionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserSubscriptionUpdate builder.
func (usu *UserSubscriptionUpdate) Where(ps ...predicate.UserSubscription) *UserSubscriptionUpdate {
	usu.mutation.Where(ps...)
	return usu
}

// SetCreatedAt sets the "created_at" field.
func (usu *UserSubscriptionUpdate) SetCreatedAt(u uint32) *UserSubscriptionUpdate {
	usu.mutation.ResetCreatedAt()
	usu.mutation.SetCreatedAt(u)
	return usu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableCreatedAt(u *uint32) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetCreatedAt(*u)
	}
	return usu
}

// AddCreatedAt adds u to the "created_at" field.
func (usu *UserSubscriptionUpdate) AddCreatedAt(u int32) *UserSubscriptionUpdate {
	usu.mutation.AddCreatedAt(u)
	return usu
}

// SetUpdatedAt sets the "updated_at" field.
func (usu *UserSubscriptionUpdate) SetUpdatedAt(u uint32) *UserSubscriptionUpdate {
	usu.mutation.ResetUpdatedAt()
	usu.mutation.SetUpdatedAt(u)
	return usu
}

// AddUpdatedAt adds u to the "updated_at" field.
func (usu *UserSubscriptionUpdate) AddUpdatedAt(u int32) *UserSubscriptionUpdate {
	usu.mutation.AddUpdatedAt(u)
	return usu
}

// SetDeletedAt sets the "deleted_at" field.
func (usu *UserSubscriptionUpdate) SetDeletedAt(u uint32) *UserSubscriptionUpdate {
	usu.mutation.ResetDeletedAt()
	usu.mutation.SetDeletedAt(u)
	return usu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableDeletedAt(u *uint32) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetDeletedAt(*u)
	}
	return usu
}

// AddDeletedAt adds u to the "deleted_at" field.
func (usu *UserSubscriptionUpdate) AddDeletedAt(u int32) *UserSubscriptionUpdate {
	usu.mutation.AddDeletedAt(u)
	return usu
}

// SetEntID sets the "ent_id" field.
func (usu *UserSubscriptionUpdate) SetEntID(u uuid.UUID) *UserSubscriptionUpdate {
	usu.mutation.SetEntID(u)
	return usu
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableEntID(u *uuid.UUID) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetEntID(*u)
	}
	return usu
}

// SetAppID sets the "app_id" field.
func (usu *UserSubscriptionUpdate) SetAppID(u uuid.UUID) *UserSubscriptionUpdate {
	usu.mutation.SetAppID(u)
	return usu
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableAppID(u *uuid.UUID) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetAppID(*u)
	}
	return usu
}

// ClearAppID clears the value of the "app_id" field.
func (usu *UserSubscriptionUpdate) ClearAppID() *UserSubscriptionUpdate {
	usu.mutation.ClearAppID()
	return usu
}

// SetUserID sets the "user_id" field.
func (usu *UserSubscriptionUpdate) SetUserID(u uuid.UUID) *UserSubscriptionUpdate {
	usu.mutation.SetUserID(u)
	return usu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableUserID(u *uuid.UUID) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetUserID(*u)
	}
	return usu
}

// ClearUserID clears the value of the "user_id" field.
func (usu *UserSubscriptionUpdate) ClearUserID() *UserSubscriptionUpdate {
	usu.mutation.ClearUserID()
	return usu
}

// SetPackageID sets the "package_id" field.
func (usu *UserSubscriptionUpdate) SetPackageID(u uuid.UUID) *UserSubscriptionUpdate {
	usu.mutation.SetPackageID(u)
	return usu
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillablePackageID(u *uuid.UUID) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetPackageID(*u)
	}
	return usu
}

// ClearPackageID clears the value of the "package_id" field.
func (usu *UserSubscriptionUpdate) ClearPackageID() *UserSubscriptionUpdate {
	usu.mutation.ClearPackageID()
	return usu
}

// SetStartAt sets the "start_at" field.
func (usu *UserSubscriptionUpdate) SetStartAt(u uint32) *UserSubscriptionUpdate {
	usu.mutation.ResetStartAt()
	usu.mutation.SetStartAt(u)
	return usu
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableStartAt(u *uint32) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetStartAt(*u)
	}
	return usu
}

// AddStartAt adds u to the "start_at" field.
func (usu *UserSubscriptionUpdate) AddStartAt(u int32) *UserSubscriptionUpdate {
	usu.mutation.AddStartAt(u)
	return usu
}

// ClearStartAt clears the value of the "start_at" field.
func (usu *UserSubscriptionUpdate) ClearStartAt() *UserSubscriptionUpdate {
	usu.mutation.ClearStartAt()
	return usu
}

// SetEndAt sets the "end_at" field.
func (usu *UserSubscriptionUpdate) SetEndAt(u uint32) *UserSubscriptionUpdate {
	usu.mutation.ResetEndAt()
	usu.mutation.SetEndAt(u)
	return usu
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableEndAt(u *uint32) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetEndAt(*u)
	}
	return usu
}

// AddEndAt adds u to the "end_at" field.
func (usu *UserSubscriptionUpdate) AddEndAt(u int32) *UserSubscriptionUpdate {
	usu.mutation.AddEndAt(u)
	return usu
}

// ClearEndAt clears the value of the "end_at" field.
func (usu *UserSubscriptionUpdate) ClearEndAt() *UserSubscriptionUpdate {
	usu.mutation.ClearEndAt()
	return usu
}

// SetUsageState sets the "usage_state" field.
func (usu *UserSubscriptionUpdate) SetUsageState(s string) *UserSubscriptionUpdate {
	usu.mutation.SetUsageState(s)
	return usu
}

// SetNillableUsageState sets the "usage_state" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableUsageState(s *string) *UserSubscriptionUpdate {
	if s != nil {
		usu.SetUsageState(*s)
	}
	return usu
}

// ClearUsageState clears the value of the "usage_state" field.
func (usu *UserSubscriptionUpdate) ClearUsageState() *UserSubscriptionUpdate {
	usu.mutation.ClearUsageState()
	return usu
}

// SetSubscriptionCredit sets the "subscription_credit" field.
func (usu *UserSubscriptionUpdate) SetSubscriptionCredit(u uint32) *UserSubscriptionUpdate {
	usu.mutation.ResetSubscriptionCredit()
	usu.mutation.SetSubscriptionCredit(u)
	return usu
}

// SetNillableSubscriptionCredit sets the "subscription_credit" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableSubscriptionCredit(u *uint32) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetSubscriptionCredit(*u)
	}
	return usu
}

// AddSubscriptionCredit adds u to the "subscription_credit" field.
func (usu *UserSubscriptionUpdate) AddSubscriptionCredit(u int32) *UserSubscriptionUpdate {
	usu.mutation.AddSubscriptionCredit(u)
	return usu
}

// ClearSubscriptionCredit clears the value of the "subscription_credit" field.
func (usu *UserSubscriptionUpdate) ClearSubscriptionCredit() *UserSubscriptionUpdate {
	usu.mutation.ClearSubscriptionCredit()
	return usu
}

// SetAddonCredit sets the "addon_credit" field.
func (usu *UserSubscriptionUpdate) SetAddonCredit(u uint32) *UserSubscriptionUpdate {
	usu.mutation.ResetAddonCredit()
	usu.mutation.SetAddonCredit(u)
	return usu
}

// SetNillableAddonCredit sets the "addon_credit" field if the given value is not nil.
func (usu *UserSubscriptionUpdate) SetNillableAddonCredit(u *uint32) *UserSubscriptionUpdate {
	if u != nil {
		usu.SetAddonCredit(*u)
	}
	return usu
}

// AddAddonCredit adds u to the "addon_credit" field.
func (usu *UserSubscriptionUpdate) AddAddonCredit(u int32) *UserSubscriptionUpdate {
	usu.mutation.AddAddonCredit(u)
	return usu
}

// ClearAddonCredit clears the value of the "addon_credit" field.
func (usu *UserSubscriptionUpdate) ClearAddonCredit() *UserSubscriptionUpdate {
	usu.mutation.ClearAddonCredit()
	return usu
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (usu *UserSubscriptionUpdate) Mutation() *UserSubscriptionMutation {
	return usu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (usu *UserSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := usu.defaults(); err != nil {
		return 0, err
	}
	if len(usu.hooks) == 0 {
		affected, err = usu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSubscriptionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usu.mutation = mutation
			affected, err = usu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(usu.hooks) - 1; i >= 0; i-- {
			if usu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = usu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usu *UserSubscriptionUpdate) defaults() error {
	if _, ok := usu.mutation.UpdatedAt(); !ok {
		if usersubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usersubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usersubscription.UpdateDefaultUpdatedAt()
		usu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (usu *UserSubscriptionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserSubscriptionUpdate {
	usu.modifiers = append(usu.modifiers, modifiers...)
	return usu
}

func (usu *UserSubscriptionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersubscription.Table,
			Columns: usersubscription.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: usersubscription.FieldID,
			},
		},
	}
	if ps := usu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldCreatedAt,
		})
	}
	if value, ok := usu.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldCreatedAt,
		})
	}
	if value, ok := usu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldUpdatedAt,
		})
	}
	if value, ok := usu.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldUpdatedAt,
		})
	}
	if value, ok := usu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldDeletedAt,
		})
	}
	if value, ok := usu.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldDeletedAt,
		})
	}
	if value, ok := usu.mutation.EntID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldEntID,
		})
	}
	if value, ok := usu.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldAppID,
		})
	}
	if usu.mutation.AppIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: usersubscription.FieldAppID,
		})
	}
	if value, ok := usu.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldUserID,
		})
	}
	if usu.mutation.UserIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: usersubscription.FieldUserID,
		})
	}
	if value, ok := usu.mutation.PackageID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldPackageID,
		})
	}
	if usu.mutation.PackageIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: usersubscription.FieldPackageID,
		})
	}
	if value, ok := usu.mutation.StartAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldStartAt,
		})
	}
	if value, ok := usu.mutation.AddedStartAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldStartAt,
		})
	}
	if usu.mutation.StartAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldStartAt,
		})
	}
	if value, ok := usu.mutation.EndAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldEndAt,
		})
	}
	if value, ok := usu.mutation.AddedEndAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldEndAt,
		})
	}
	if usu.mutation.EndAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldEndAt,
		})
	}
	if value, ok := usu.mutation.UsageState(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usersubscription.FieldUsageState,
		})
	}
	if usu.mutation.UsageStateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: usersubscription.FieldUsageState,
		})
	}
	if value, ok := usu.mutation.SubscriptionCredit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldSubscriptionCredit,
		})
	}
	if value, ok := usu.mutation.AddedSubscriptionCredit(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldSubscriptionCredit,
		})
	}
	if usu.mutation.SubscriptionCreditCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldSubscriptionCredit,
		})
	}
	if value, ok := usu.mutation.AddonCredit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldAddonCredit,
		})
	}
	if value, ok := usu.mutation.AddedAddonCredit(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldAddonCredit,
		})
	}
	if usu.mutation.AddonCreditCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldAddonCredit,
		})
	}
	_spec.Modifiers = usu.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// UserSubscriptionUpdateOne is the builder for updating a single UserSubscription entity.
type UserSubscriptionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserSubscriptionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (usuo *UserSubscriptionUpdateOne) SetCreatedAt(u uint32) *UserSubscriptionUpdateOne {
	usuo.mutation.ResetCreatedAt()
	usuo.mutation.SetCreatedAt(u)
	return usuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableCreatedAt(u *uint32) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetCreatedAt(*u)
	}
	return usuo
}

// AddCreatedAt adds u to the "created_at" field.
func (usuo *UserSubscriptionUpdateOne) AddCreatedAt(u int32) *UserSubscriptionUpdateOne {
	usuo.mutation.AddCreatedAt(u)
	return usuo
}

// SetUpdatedAt sets the "updated_at" field.
func (usuo *UserSubscriptionUpdateOne) SetUpdatedAt(u uint32) *UserSubscriptionUpdateOne {
	usuo.mutation.ResetUpdatedAt()
	usuo.mutation.SetUpdatedAt(u)
	return usuo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (usuo *UserSubscriptionUpdateOne) AddUpdatedAt(u int32) *UserSubscriptionUpdateOne {
	usuo.mutation.AddUpdatedAt(u)
	return usuo
}

// SetDeletedAt sets the "deleted_at" field.
func (usuo *UserSubscriptionUpdateOne) SetDeletedAt(u uint32) *UserSubscriptionUpdateOne {
	usuo.mutation.ResetDeletedAt()
	usuo.mutation.SetDeletedAt(u)
	return usuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableDeletedAt(u *uint32) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetDeletedAt(*u)
	}
	return usuo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (usuo *UserSubscriptionUpdateOne) AddDeletedAt(u int32) *UserSubscriptionUpdateOne {
	usuo.mutation.AddDeletedAt(u)
	return usuo
}

// SetEntID sets the "ent_id" field.
func (usuo *UserSubscriptionUpdateOne) SetEntID(u uuid.UUID) *UserSubscriptionUpdateOne {
	usuo.mutation.SetEntID(u)
	return usuo
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableEntID(u *uuid.UUID) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetEntID(*u)
	}
	return usuo
}

// SetAppID sets the "app_id" field.
func (usuo *UserSubscriptionUpdateOne) SetAppID(u uuid.UUID) *UserSubscriptionUpdateOne {
	usuo.mutation.SetAppID(u)
	return usuo
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableAppID(u *uuid.UUID) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetAppID(*u)
	}
	return usuo
}

// ClearAppID clears the value of the "app_id" field.
func (usuo *UserSubscriptionUpdateOne) ClearAppID() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearAppID()
	return usuo
}

// SetUserID sets the "user_id" field.
func (usuo *UserSubscriptionUpdateOne) SetUserID(u uuid.UUID) *UserSubscriptionUpdateOne {
	usuo.mutation.SetUserID(u)
	return usuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableUserID(u *uuid.UUID) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetUserID(*u)
	}
	return usuo
}

// ClearUserID clears the value of the "user_id" field.
func (usuo *UserSubscriptionUpdateOne) ClearUserID() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearUserID()
	return usuo
}

// SetPackageID sets the "package_id" field.
func (usuo *UserSubscriptionUpdateOne) SetPackageID(u uuid.UUID) *UserSubscriptionUpdateOne {
	usuo.mutation.SetPackageID(u)
	return usuo
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillablePackageID(u *uuid.UUID) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetPackageID(*u)
	}
	return usuo
}

// ClearPackageID clears the value of the "package_id" field.
func (usuo *UserSubscriptionUpdateOne) ClearPackageID() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearPackageID()
	return usuo
}

// SetStartAt sets the "start_at" field.
func (usuo *UserSubscriptionUpdateOne) SetStartAt(u uint32) *UserSubscriptionUpdateOne {
	usuo.mutation.ResetStartAt()
	usuo.mutation.SetStartAt(u)
	return usuo
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableStartAt(u *uint32) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetStartAt(*u)
	}
	return usuo
}

// AddStartAt adds u to the "start_at" field.
func (usuo *UserSubscriptionUpdateOne) AddStartAt(u int32) *UserSubscriptionUpdateOne {
	usuo.mutation.AddStartAt(u)
	return usuo
}

// ClearStartAt clears the value of the "start_at" field.
func (usuo *UserSubscriptionUpdateOne) ClearStartAt() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearStartAt()
	return usuo
}

// SetEndAt sets the "end_at" field.
func (usuo *UserSubscriptionUpdateOne) SetEndAt(u uint32) *UserSubscriptionUpdateOne {
	usuo.mutation.ResetEndAt()
	usuo.mutation.SetEndAt(u)
	return usuo
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableEndAt(u *uint32) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetEndAt(*u)
	}
	return usuo
}

// AddEndAt adds u to the "end_at" field.
func (usuo *UserSubscriptionUpdateOne) AddEndAt(u int32) *UserSubscriptionUpdateOne {
	usuo.mutation.AddEndAt(u)
	return usuo
}

// ClearEndAt clears the value of the "end_at" field.
func (usuo *UserSubscriptionUpdateOne) ClearEndAt() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearEndAt()
	return usuo
}

// SetUsageState sets the "usage_state" field.
func (usuo *UserSubscriptionUpdateOne) SetUsageState(s string) *UserSubscriptionUpdateOne {
	usuo.mutation.SetUsageState(s)
	return usuo
}

// SetNillableUsageState sets the "usage_state" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableUsageState(s *string) *UserSubscriptionUpdateOne {
	if s != nil {
		usuo.SetUsageState(*s)
	}
	return usuo
}

// ClearUsageState clears the value of the "usage_state" field.
func (usuo *UserSubscriptionUpdateOne) ClearUsageState() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearUsageState()
	return usuo
}

// SetSubscriptionCredit sets the "subscription_credit" field.
func (usuo *UserSubscriptionUpdateOne) SetSubscriptionCredit(u uint32) *UserSubscriptionUpdateOne {
	usuo.mutation.ResetSubscriptionCredit()
	usuo.mutation.SetSubscriptionCredit(u)
	return usuo
}

// SetNillableSubscriptionCredit sets the "subscription_credit" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableSubscriptionCredit(u *uint32) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetSubscriptionCredit(*u)
	}
	return usuo
}

// AddSubscriptionCredit adds u to the "subscription_credit" field.
func (usuo *UserSubscriptionUpdateOne) AddSubscriptionCredit(u int32) *UserSubscriptionUpdateOne {
	usuo.mutation.AddSubscriptionCredit(u)
	return usuo
}

// ClearSubscriptionCredit clears the value of the "subscription_credit" field.
func (usuo *UserSubscriptionUpdateOne) ClearSubscriptionCredit() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearSubscriptionCredit()
	return usuo
}

// SetAddonCredit sets the "addon_credit" field.
func (usuo *UserSubscriptionUpdateOne) SetAddonCredit(u uint32) *UserSubscriptionUpdateOne {
	usuo.mutation.ResetAddonCredit()
	usuo.mutation.SetAddonCredit(u)
	return usuo
}

// SetNillableAddonCredit sets the "addon_credit" field if the given value is not nil.
func (usuo *UserSubscriptionUpdateOne) SetNillableAddonCredit(u *uint32) *UserSubscriptionUpdateOne {
	if u != nil {
		usuo.SetAddonCredit(*u)
	}
	return usuo
}

// AddAddonCredit adds u to the "addon_credit" field.
func (usuo *UserSubscriptionUpdateOne) AddAddonCredit(u int32) *UserSubscriptionUpdateOne {
	usuo.mutation.AddAddonCredit(u)
	return usuo
}

// ClearAddonCredit clears the value of the "addon_credit" field.
func (usuo *UserSubscriptionUpdateOne) ClearAddonCredit() *UserSubscriptionUpdateOne {
	usuo.mutation.ClearAddonCredit()
	return usuo
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (usuo *UserSubscriptionUpdateOne) Mutation() *UserSubscriptionMutation {
	return usuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (usuo *UserSubscriptionUpdateOne) Select(field string, fields ...string) *UserSubscriptionUpdateOne {
	usuo.fields = append([]string{field}, fields...)
	return usuo
}

// Save executes the query and returns the updated UserSubscription entity.
func (usuo *UserSubscriptionUpdateOne) Save(ctx context.Context) (*UserSubscription, error) {
	var (
		err  error
		node *UserSubscription
	)
	if err := usuo.defaults(); err != nil {
		return nil, err
	}
	if len(usuo.hooks) == 0 {
		node, err = usuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSubscriptionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usuo.mutation = mutation
			node, err = usuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(usuo.hooks) - 1; i >= 0; i-- {
			if usuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = usuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, usuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*UserSubscription)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserSubscriptionMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserSubscriptionUpdateOne) SaveX(ctx context.Context) *UserSubscription {
	node, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (usuo *UserSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usuo *UserSubscriptionUpdateOne) defaults() error {
	if _, ok := usuo.mutation.UpdatedAt(); !ok {
		if usersubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usersubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usersubscription.UpdateDefaultUpdatedAt()
		usuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (usuo *UserSubscriptionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserSubscriptionUpdateOne {
	usuo.modifiers = append(usuo.modifiers, modifiers...)
	return usuo
}

func (usuo *UserSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *UserSubscription, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersubscription.Table,
			Columns: usersubscription.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: usersubscription.FieldID,
			},
		},
	}
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := usuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscription.FieldID)
		for _, f := range fields {
			if !usersubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := usuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldCreatedAt,
		})
	}
	if value, ok := usuo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldCreatedAt,
		})
	}
	if value, ok := usuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldUpdatedAt,
		})
	}
	if value, ok := usuo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldUpdatedAt,
		})
	}
	if value, ok := usuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldDeletedAt,
		})
	}
	if value, ok := usuo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldDeletedAt,
		})
	}
	if value, ok := usuo.mutation.EntID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldEntID,
		})
	}
	if value, ok := usuo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldAppID,
		})
	}
	if usuo.mutation.AppIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: usersubscription.FieldAppID,
		})
	}
	if value, ok := usuo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldUserID,
		})
	}
	if usuo.mutation.UserIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: usersubscription.FieldUserID,
		})
	}
	if value, ok := usuo.mutation.PackageID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersubscription.FieldPackageID,
		})
	}
	if usuo.mutation.PackageIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: usersubscription.FieldPackageID,
		})
	}
	if value, ok := usuo.mutation.StartAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldStartAt,
		})
	}
	if value, ok := usuo.mutation.AddedStartAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldStartAt,
		})
	}
	if usuo.mutation.StartAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldStartAt,
		})
	}
	if value, ok := usuo.mutation.EndAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldEndAt,
		})
	}
	if value, ok := usuo.mutation.AddedEndAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldEndAt,
		})
	}
	if usuo.mutation.EndAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldEndAt,
		})
	}
	if value, ok := usuo.mutation.UsageState(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usersubscription.FieldUsageState,
		})
	}
	if usuo.mutation.UsageStateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: usersubscription.FieldUsageState,
		})
	}
	if value, ok := usuo.mutation.SubscriptionCredit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldSubscriptionCredit,
		})
	}
	if value, ok := usuo.mutation.AddedSubscriptionCredit(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldSubscriptionCredit,
		})
	}
	if usuo.mutation.SubscriptionCreditCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldSubscriptionCredit,
		})
	}
	if value, ok := usuo.mutation.AddonCredit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldAddonCredit,
		})
	}
	if value, ok := usuo.mutation.AddedAddonCredit(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersubscription.FieldAddonCredit,
		})
	}
	if usuo.mutation.AddonCreditCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: usersubscription.FieldAddonCredit,
		})
	}
	_spec.Modifiers = usuo.modifiers
	_node = &UserSubscription{config: usuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
