// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/usersubscription"
)

// UserSubscriptionQuery is the builder for querying UserSubscription entities.
type UserSubscriptionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserSubscription
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserSubscriptionQuery builder.
func (usq *UserSubscriptionQuery) Where(ps ...predicate.UserSubscription) *UserSubscriptionQuery {
	usq.predicates = append(usq.predicates, ps...)
	return usq
}

// Limit adds a limit step to the query.
func (usq *UserSubscriptionQuery) Limit(limit int) *UserSubscriptionQuery {
	usq.limit = &limit
	return usq
}

// Offset adds an offset step to the query.
func (usq *UserSubscriptionQuery) Offset(offset int) *UserSubscriptionQuery {
	usq.offset = &offset
	return usq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (usq *UserSubscriptionQuery) Unique(unique bool) *UserSubscriptionQuery {
	usq.unique = &unique
	return usq
}

// Order adds an order step to the query.
func (usq *UserSubscriptionQuery) Order(o ...OrderFunc) *UserSubscriptionQuery {
	usq.order = append(usq.order, o...)
	return usq
}

// First returns the first UserSubscription entity from the query.
// Returns a *NotFoundError when no UserSubscription was found.
func (usq *UserSubscriptionQuery) First(ctx context.Context) (*UserSubscription, error) {
	nodes, err := usq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersubscription.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (usq *UserSubscriptionQuery) FirstX(ctx context.Context) *UserSubscription {
	node, err := usq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserSubscription ID from the query.
// Returns a *NotFoundError when no UserSubscription ID was found.
func (usq *UserSubscriptionQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = usq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersubscription.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (usq *UserSubscriptionQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := usq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserSubscription entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserSubscription entity is found.
// Returns a *NotFoundError when no UserSubscription entities are found.
func (usq *UserSubscriptionQuery) Only(ctx context.Context) (*UserSubscription, error) {
	nodes, err := usq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersubscription.Label}
	default:
		return nil, &NotSingularError{usersubscription.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (usq *UserSubscriptionQuery) OnlyX(ctx context.Context) *UserSubscription {
	node, err := usq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserSubscription ID in the query.
// Returns a *NotSingularError when more than one UserSubscription ID is found.
// Returns a *NotFoundError when no entities are found.
func (usq *UserSubscriptionQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = usq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersubscription.Label}
	default:
		err = &NotSingularError{usersubscription.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (usq *UserSubscriptionQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := usq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserSubscriptions.
func (usq *UserSubscriptionQuery) All(ctx context.Context) ([]*UserSubscription, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return usq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (usq *UserSubscriptionQuery) AllX(ctx context.Context) []*UserSubscription {
	nodes, err := usq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserSubscription IDs.
func (usq *UserSubscriptionQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := usq.Select(usersubscription.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (usq *UserSubscriptionQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := usq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (usq *UserSubscriptionQuery) Count(ctx context.Context) (int, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return usq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (usq *UserSubscriptionQuery) CountX(ctx context.Context) int {
	count, err := usq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (usq *UserSubscriptionQuery) Exist(ctx context.Context) (bool, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return usq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (usq *UserSubscriptionQuery) ExistX(ctx context.Context) bool {
	exist, err := usq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserSubscriptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (usq *UserSubscriptionQuery) Clone() *UserSubscriptionQuery {
	if usq == nil {
		return nil
	}
	return &UserSubscriptionQuery{
		config:     usq.config,
		limit:      usq.limit,
		offset:     usq.offset,
		order:      append([]OrderFunc{}, usq.order...),
		predicates: append([]predicate.UserSubscription{}, usq.predicates...),
		// clone intermediate query.
		sql:    usq.sql.Clone(),
		path:   usq.path,
		unique: usq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserSubscription.Query().
//		GroupBy(usersubscription.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (usq *UserSubscriptionQuery) GroupBy(field string, fields ...string) *UserSubscriptionGroupBy {
	grbuild := &UserSubscriptionGroupBy{config: usq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := usq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return usq.sqlQuery(ctx), nil
	}
	grbuild.label = usersubscription.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.UserSubscription.Query().
//		Select(usersubscription.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (usq *UserSubscriptionQuery) Select(fields ...string) *UserSubscriptionSelect {
	usq.fields = append(usq.fields, fields...)
	selbuild := &UserSubscriptionSelect{UserSubscriptionQuery: usq}
	selbuild.label = usersubscription.Label
	selbuild.flds, selbuild.scan = &usq.fields, selbuild.Scan
	return selbuild
}

func (usq *UserSubscriptionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range usq.fields {
		if !usersubscription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if usq.path != nil {
		prev, err := usq.path(ctx)
		if err != nil {
			return err
		}
		usq.sql = prev
	}
	if usersubscription.Policy == nil {
		return errors.New("ent: uninitialized usersubscription.Policy (forgotten import ent/runtime?)")
	}
	if err := usersubscription.Policy.EvalQuery(ctx, usq); err != nil {
		return err
	}
	return nil
}

func (usq *UserSubscriptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserSubscription, error) {
	var (
		nodes = []*UserSubscription{}
		_spec = usq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*UserSubscription).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &UserSubscription{config: usq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(usq.modifiers) > 0 {
		_spec.Modifiers = usq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, usq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (usq *UserSubscriptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := usq.querySpec()
	if len(usq.modifiers) > 0 {
		_spec.Modifiers = usq.modifiers
	}
	_spec.Node.Columns = usq.fields
	if len(usq.fields) > 0 {
		_spec.Unique = usq.unique != nil && *usq.unique
	}
	return sqlgraph.CountNodes(ctx, usq.driver, _spec)
}

func (usq *UserSubscriptionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := usq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (usq *UserSubscriptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersubscription.Table,
			Columns: usersubscription.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: usersubscription.FieldID,
			},
		},
		From:   usq.sql,
		Unique: true,
	}
	if unique := usq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := usq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscription.FieldID)
		for i := range fields {
			if fields[i] != usersubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := usq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := usq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := usq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := usq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (usq *UserSubscriptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(usq.driver.Dialect())
	t1 := builder.Table(usersubscription.Table)
	columns := usq.fields
	if len(columns) == 0 {
		columns = usersubscription.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if usq.sql != nil {
		selector = usq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if usq.unique != nil && *usq.unique {
		selector.Distinct()
	}
	for _, m := range usq.modifiers {
		m(selector)
	}
	for _, p := range usq.predicates {
		p(selector)
	}
	for _, p := range usq.order {
		p(selector)
	}
	if offset := usq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := usq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (usq *UserSubscriptionQuery) ForUpdate(opts ...sql.LockOption) *UserSubscriptionQuery {
	if usq.driver.Dialect() == dialect.Postgres {
		usq.Unique(false)
	}
	usq.modifiers = append(usq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return usq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (usq *UserSubscriptionQuery) ForShare(opts ...sql.LockOption) *UserSubscriptionQuery {
	if usq.driver.Dialect() == dialect.Postgres {
		usq.Unique(false)
	}
	usq.modifiers = append(usq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return usq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (usq *UserSubscriptionQuery) Modify(modifiers ...func(s *sql.Selector)) *UserSubscriptionSelect {
	usq.modifiers = append(usq.modifiers, modifiers...)
	return usq.Select()
}

// UserSubscriptionGroupBy is the group-by builder for UserSubscription entities.
type UserSubscriptionGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (usgb *UserSubscriptionGroupBy) Aggregate(fns ...AggregateFunc) *UserSubscriptionGroupBy {
	usgb.fns = append(usgb.fns, fns...)
	return usgb
}

// Scan applies the group-by query and scans the result into the given value.
func (usgb *UserSubscriptionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := usgb.path(ctx)
	if err != nil {
		return err
	}
	usgb.sql = query
	return usgb.sqlScan(ctx, v)
}

func (usgb *UserSubscriptionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range usgb.fields {
		if !usersubscription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := usgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := usgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (usgb *UserSubscriptionGroupBy) sqlQuery() *sql.Selector {
	selector := usgb.sql.Select()
	aggregation := make([]string, 0, len(usgb.fns))
	for _, fn := range usgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(usgb.fields)+len(usgb.fns))
		for _, f := range usgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(usgb.fields...)...)
}

// UserSubscriptionSelect is the builder for selecting fields of UserSubscription entities.
type UserSubscriptionSelect struct {
	*UserSubscriptionQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uss *UserSubscriptionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uss.prepareQuery(ctx); err != nil {
		return err
	}
	uss.sql = uss.UserSubscriptionQuery.sqlQuery(ctx)
	return uss.sqlScan(ctx, v)
}

func (uss *UserSubscriptionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uss.sql.Query()
	if err := uss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (uss *UserSubscriptionSelect) Modify(modifiers ...func(s *sql.Selector)) *UserSubscriptionSelect {
	uss.modifiers = append(uss.modifiers, modifiers...)
	return uss
}
