// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/billing-middleware/pkg/db/ent/usersubscriptionchange"
)

// UserSubscriptionChangeQuery is the builder for querying UserSubscriptionChange entities.
type UserSubscriptionChangeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserSubscriptionChange
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserSubscriptionChangeQuery builder.
func (uscq *UserSubscriptionChangeQuery) Where(ps ...predicate.UserSubscriptionChange) *UserSubscriptionChangeQuery {
	uscq.predicates = append(uscq.predicates, ps...)
	return uscq
}

// Limit adds a limit step to the query.
func (uscq *UserSubscriptionChangeQuery) Limit(limit int) *UserSubscriptionChangeQuery {
	uscq.limit = &limit
	return uscq
}

// Offset adds an offset step to the query.
func (uscq *UserSubscriptionChangeQuery) Offset(offset int) *UserSubscriptionChangeQuery {
	uscq.offset = &offset
	return uscq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uscq *UserSubscriptionChangeQuery) Unique(unique bool) *UserSubscriptionChangeQuery {
	uscq.unique = &unique
	return uscq
}

// Order adds an order step to the query.
func (uscq *UserSubscriptionChangeQuery) Order(o ...OrderFunc) *UserSubscriptionChangeQuery {
	uscq.order = append(uscq.order, o...)
	return uscq
}

// First returns the first UserSubscriptionChange entity from the query.
// Returns a *NotFoundError when no UserSubscriptionChange was found.
func (uscq *UserSubscriptionChangeQuery) First(ctx context.Context) (*UserSubscriptionChange, error) {
	nodes, err := uscq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersubscriptionchange.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) FirstX(ctx context.Context) *UserSubscriptionChange {
	node, err := uscq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserSubscriptionChange ID from the query.
// Returns a *NotFoundError when no UserSubscriptionChange ID was found.
func (uscq *UserSubscriptionChangeQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = uscq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersubscriptionchange.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := uscq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserSubscriptionChange entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserSubscriptionChange entity is found.
// Returns a *NotFoundError when no UserSubscriptionChange entities are found.
func (uscq *UserSubscriptionChangeQuery) Only(ctx context.Context) (*UserSubscriptionChange, error) {
	nodes, err := uscq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersubscriptionchange.Label}
	default:
		return nil, &NotSingularError{usersubscriptionchange.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) OnlyX(ctx context.Context) *UserSubscriptionChange {
	node, err := uscq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserSubscriptionChange ID in the query.
// Returns a *NotSingularError when more than one UserSubscriptionChange ID is found.
// Returns a *NotFoundError when no entities are found.
func (uscq *UserSubscriptionChangeQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = uscq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersubscriptionchange.Label}
	default:
		err = &NotSingularError{usersubscriptionchange.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := uscq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserSubscriptionChanges.
func (uscq *UserSubscriptionChangeQuery) All(ctx context.Context) ([]*UserSubscriptionChange, error) {
	if err := uscq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uscq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) AllX(ctx context.Context) []*UserSubscriptionChange {
	nodes, err := uscq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserSubscriptionChange IDs.
func (uscq *UserSubscriptionChangeQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := uscq.Select(usersubscriptionchange.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := uscq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uscq *UserSubscriptionChangeQuery) Count(ctx context.Context) (int, error) {
	if err := uscq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uscq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) CountX(ctx context.Context) int {
	count, err := uscq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uscq *UserSubscriptionChangeQuery) Exist(ctx context.Context) (bool, error) {
	if err := uscq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uscq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uscq *UserSubscriptionChangeQuery) ExistX(ctx context.Context) bool {
	exist, err := uscq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserSubscriptionChangeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uscq *UserSubscriptionChangeQuery) Clone() *UserSubscriptionChangeQuery {
	if uscq == nil {
		return nil
	}
	return &UserSubscriptionChangeQuery{
		config:     uscq.config,
		limit:      uscq.limit,
		offset:     uscq.offset,
		order:      append([]OrderFunc{}, uscq.order...),
		predicates: append([]predicate.UserSubscriptionChange{}, uscq.predicates...),
		// clone intermediate query.
		sql:    uscq.sql.Clone(),
		path:   uscq.path,
		unique: uscq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserSubscriptionChange.Query().
//		GroupBy(usersubscriptionchange.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uscq *UserSubscriptionChangeQuery) GroupBy(field string, fields ...string) *UserSubscriptionChangeGroupBy {
	grbuild := &UserSubscriptionChangeGroupBy{config: uscq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uscq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uscq.sqlQuery(ctx), nil
	}
	grbuild.label = usersubscriptionchange.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.UserSubscriptionChange.Query().
//		Select(usersubscriptionchange.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (uscq *UserSubscriptionChangeQuery) Select(fields ...string) *UserSubscriptionChangeSelect {
	uscq.fields = append(uscq.fields, fields...)
	selbuild := &UserSubscriptionChangeSelect{UserSubscriptionChangeQuery: uscq}
	selbuild.label = usersubscriptionchange.Label
	selbuild.flds, selbuild.scan = &uscq.fields, selbuild.Scan
	return selbuild
}

func (uscq *UserSubscriptionChangeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uscq.fields {
		if !usersubscriptionchange.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uscq.path != nil {
		prev, err := uscq.path(ctx)
		if err != nil {
			return err
		}
		uscq.sql = prev
	}
	if usersubscriptionchange.Policy == nil {
		return errors.New("ent: uninitialized usersubscriptionchange.Policy (forgotten import ent/runtime?)")
	}
	if err := usersubscriptionchange.Policy.EvalQuery(ctx, uscq); err != nil {
		return err
	}
	return nil
}

func (uscq *UserSubscriptionChangeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserSubscriptionChange, error) {
	var (
		nodes = []*UserSubscriptionChange{}
		_spec = uscq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*UserSubscriptionChange).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &UserSubscriptionChange{config: uscq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(uscq.modifiers) > 0 {
		_spec.Modifiers = uscq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uscq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uscq *UserSubscriptionChangeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uscq.querySpec()
	if len(uscq.modifiers) > 0 {
		_spec.Modifiers = uscq.modifiers
	}
	_spec.Node.Columns = uscq.fields
	if len(uscq.fields) > 0 {
		_spec.Unique = uscq.unique != nil && *uscq.unique
	}
	return sqlgraph.CountNodes(ctx, uscq.driver, _spec)
}

func (uscq *UserSubscriptionChangeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uscq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uscq *UserSubscriptionChangeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersubscriptionchange.Table,
			Columns: usersubscriptionchange.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: usersubscriptionchange.FieldID,
			},
		},
		From:   uscq.sql,
		Unique: true,
	}
	if unique := uscq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uscq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscriptionchange.FieldID)
		for i := range fields {
			if fields[i] != usersubscriptionchange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uscq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uscq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uscq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uscq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uscq *UserSubscriptionChangeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uscq.driver.Dialect())
	t1 := builder.Table(usersubscriptionchange.Table)
	columns := uscq.fields
	if len(columns) == 0 {
		columns = usersubscriptionchange.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uscq.sql != nil {
		selector = uscq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uscq.unique != nil && *uscq.unique {
		selector.Distinct()
	}
	for _, m := range uscq.modifiers {
		m(selector)
	}
	for _, p := range uscq.predicates {
		p(selector)
	}
	for _, p := range uscq.order {
		p(selector)
	}
	if offset := uscq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uscq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (uscq *UserSubscriptionChangeQuery) ForUpdate(opts ...sql.LockOption) *UserSubscriptionChangeQuery {
	if uscq.driver.Dialect() == dialect.Postgres {
		uscq.Unique(false)
	}
	uscq.modifiers = append(uscq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return uscq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (uscq *UserSubscriptionChangeQuery) ForShare(opts ...sql.LockOption) *UserSubscriptionChangeQuery {
	if uscq.driver.Dialect() == dialect.Postgres {
		uscq.Unique(false)
	}
	uscq.modifiers = append(uscq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return uscq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (uscq *UserSubscriptionChangeQuery) Modify(modifiers ...func(s *sql.Selector)) *UserSubscriptionChangeSelect {
	uscq.modifiers = append(uscq.modifiers, modifiers...)
	return uscq.Select()
}

// UserSubscriptionChangeGroupBy is the group-by builder for UserSubscriptionChange entities.
type UserSubscriptionChangeGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uscgb *UserSubscriptionChangeGroupBy) Aggregate(fns ...AggregateFunc) *UserSubscriptionChangeGroupBy {
	uscgb.fns = append(uscgb.fns, fns...)
	return uscgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uscgb *UserSubscriptionChangeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uscgb.path(ctx)
	if err != nil {
		return err
	}
	uscgb.sql = query
	return uscgb.sqlScan(ctx, v)
}

func (uscgb *UserSubscriptionChangeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uscgb.fields {
		if !usersubscriptionchange.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uscgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uscgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uscgb *UserSubscriptionChangeGroupBy) sqlQuery() *sql.Selector {
	selector := uscgb.sql.Select()
	aggregation := make([]string, 0, len(uscgb.fns))
	for _, fn := range uscgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uscgb.fields)+len(uscgb.fns))
		for _, f := range uscgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uscgb.fields...)...)
}

// UserSubscriptionChangeSelect is the builder for selecting fields of UserSubscriptionChange entities.
type UserSubscriptionChangeSelect struct {
	*UserSubscriptionChangeQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uscs *UserSubscriptionChangeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uscs.prepareQuery(ctx); err != nil {
		return err
	}
	uscs.sql = uscs.UserSubscriptionChangeQuery.sqlQuery(ctx)
	return uscs.sqlScan(ctx, v)
}

func (uscs *UserSubscriptionChangeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uscs.sql.Query()
	if err := uscs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (uscs *UserSubscriptionChangeSelect) Modify(modifiers ...func(s *sql.Selector)) *UserSubscriptionChangeSelect {
	uscs.modifiers = append(uscs.modifiers, modifiers...)
	return uscs
}
